name: Run check expected count script on changed queries

on:
  pull_request:
    paths:
      - '**/*.rq' # Only run when .rq files are modified

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check changed .rq files
      id: check-files
      run: |
        # Get a list of .rq files changed in the PR
        CHANGED_FILES=$(git diff --name-only origin/main...HEAD -- '*.rq')
        for file in $CHANGED_FILES; do
          echo "Running script on $file"
          python scripts/check-expected-results-count.py --path "$file"
        done
